config/routes.rb
class TurkerConstraint
  def initialize
    @turker_host_names = ['lvh.me', 'turker.zenlike.me', 'makemeeting.info']
  end
 
  def matches?(request)
    @turker_host_names.include?(request.host)
  end
end

class RegularUserConstraint
  def initialize
    @regular_host_names = ['localhost', 'zenlike.herokuapp.com','meetings.zenlike.me']
  end
 
  def matches?(request)
    @regular_host_names.include?(request.host)
  end
end

Zenlike::Application.routes.draw do

  get "home/index"

  
  
  
  get 'meeting_thread_jobs' => 'meeting_thread_jobs#index', :as => 'meeting_thread_jobs'
  get 'meeting_thread_jobs/:id' => 'meeting_thread_jobs#show', :as => 'meeting_thread_job' 
  resources :calendar_guesses
    
  constraints RegularUserConstraint.new do
    
      resources :meeting_threads do
        collection do
          post 'from_sendgrid'
        end
      end

  end

  root :to => "home#index"

  mount StripeEvent::Engine => '/stripe'
      
  devise_for :users, :controllers => { :subscriptions => 'subscriptions' }
  
  resources :users

  resources :subscriptions
  
  put 'update_plan', :to => 'subscriptions#update_plan'
  put 'update_card', :to => 'subscriptions#update_card'
  resources :plans

  match 'auth/:provider/callback', to: 'oauth_sessions#create'
  match 'auth/failure', to: redirect('/')
  

end

app/controllers/calendar_guesses_controller.rb
class CalendarGuessesController < ApplicationController
  layout 'turker_application'
  
  load_and_authorize_resource
  
  # GET /callendar_guesses.html
  # GET /meeting_threads.json
  def index
    #@meeting_threads = MeetingThread.all

    @calendar_guesses = @current_user.calendar_guesses
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendar_guesses }
    end
  end

  # GET /calendar_guesses/1
  # GET /calendar_guesses/1.json
  def show
    #@calendar_guess = CalendarGuess.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calendar_guess }
    end
  end

  # GET /calendar_guesses/new
  # GET /calendar_guesses/new.json
  def new
    #@calendar_guess = CalendarGuess.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calendar_guess }
    end
  end

  # GET /calendar_guesses/1/edit
  def edit
    #@calendar_guess = CalendarGuess.find(params[:id])
    @calendar_guess.turker = @current_user
  end

  # POST /calendar_guess
  # POST /calendar_guess.json
  def create
    #@calendar_guess = CalendarGuess.new(params[:calendar_guess])
    
    respond_to do |format|
      if @calendar_guess.save
        format.html { redirect_to meeting_thread_jobs_url }
        format.json { render json: @calendar_guess, status: :created, location: @calendar_guess }
      else
        format.html { render action: "new" }
        format.json { render json: @calendar_guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calendar_guess/1
  # PUT /calendar_guess/1.json
  def update
    #@calendar_guess = CalendarGuess.find(params[:id])

    respond_to do |format|
      if @@calendar_guess.update_attributes(params[:calendar_guess])
        format.html { redirect_to @calendar_guess, notice: 'Calendar guess was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @calendar_guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendar_guess/1
  # DELETE /calendar_guess/1.json
  def destroy
    #@calendar_guess = CalendarGuess.find(params[:id])
    @calendar_guess.destroy

    respond_to do |format|
      format.html { redirect_to meeting_thread_jobs_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/calendar_guesses_helper.rb
module CalendarGuessesHelper
end

app/views/calendar_guesses/_calendar_guess_form.html.erb
<%= simple_form_for(@calendar_guess, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @calendar_guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar_guess.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% @calendar_guess.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :turker_id, :value => @current_user.id %>	
  <%= f.hidden_field :meeting_thread_id, :value => @calendar_guess.meeting_thread.id %>	
  	<fieldset>
		<legend>Fill out meeting info</legend>
		<%= f.input :participants, :hint => "Comma separated list of email addresses", :required => true %>
		<!--
		<%= f.input :start_date_time, :as => :string,  :required => true%>
		<%= f.input :end_date_time, :as => :string, :required => true, input_html: { size: 20 } %>
		-->

		<%= f.input :start_date_time, :required => true%>
		<%= f.input :end_date_time, :required => true%>

	 	<%= f.input :time_zone, priority: /US/, :required => true%>


	    <%= f.input :location, :required => true %><br />
	    <%= f.input :summary, :hint => "Participant1, Participant2 - Location - Time", :size => 80, :required => true %>
	    <%= f.input :description, :size => 80, :required => true %>
		<%= f.button :submit, 'Submit', :class => 'btn-primary' %> 
	</fieldset>

<% end %>

app/views/calendar_guesses/_meeting_thread_job_form.html.erb
<%= form_for(@calendar_guess) do |f| %>
  <% if @calendar_guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar_guess.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% @calendar_guess.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :turker_id, :value => @current_user.id %>	
	<%= f.hidden_field :meeting_thread_id, :value => @calendar_guess.meeting_thread.id %>	
  <div class="field">
    <%= f.label :participants %><br />
    <%= f.text_field :participants %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "60X12" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendar_guesses/edit.html.erb
<h1>Editing Calendar guess</h1>

<%= render 'meeting_thread_job_form' %>

<%= link_to 'Show', @calendar_guess %> |

app/views/calendar_guesses/index.html.erb
<h2>Calendar guesses</h2>

<table>
  <tr>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Location</th>
    <th>participants</th>
    <th>Summary</th>
    <th>Description</th>
  </tr>

<% @calendar_guesses.each do |calendar_guess| %>
  <tr>
    <td><%= calendar_guess.start_time %></td>	
    <td><%= calendar_guess.end_time %></td>	
    <td><%= calendar_guess.location %></td>
    <td><%= calendar_guess.participants %></td>
    <td><%= calendar_guess.summary %></td>
    <td><%= calendar_guess.description %></td>
  </tr>
<% end %>
</table>

<br />

app/views/calendar_guesses/new.html.erb
<h1>New Calendar guess</h1>

<%= render 'calendar_guess_form' %>

app/views/calendar_guesses/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Participants:</b>
  <%= @calendar_guess.participants %>
</p>

<p>
  <b>Start Time:</b>
  <%= @calendar_guess.start_time %>
</p>
<p>
  <b>End Time:</b>
  <%= @calendar_guess.end_time %>
</p>

<p>
  <b>Location:</b>
  <%= @calendar_guess.location %>
</p>
<p>
  <b>Summary:</b>
  <%= @calendar_guess.summary %>
</p>
<p>
  <b>Description:</b>
  <%= @calendar_guess.description %>
</p>

<%= link_to 'Edit', edit_calendar_guess_path(@calendar_guess) %>