config/routes.rb
class TurkerConstraint
  def initialize
    @turker_host_names = ['lvh.me', 'turker.zenlike.me', 'makemeeting.info']
  end
 
  def matches?(request)
    @turker_host_names.include?(request.host)
  end
end

class RegularUserConstraint
  def initialize
    @regular_host_names = ['localhost', 'zenlike.herokuapp.com','meetings.zenlike.me']
  end
 
  def matches?(request)
    @regular_host_names.include?(request.host)
  end
end

Zenlike::Application.routes.draw do

  get "home/index"

  
  
  
  get 'meeting_thread_jobs' => 'meeting_thread_jobs#index', :as => 'meeting_thread_jobs'
  get 'meeting_thread_jobs/:id' => 'meeting_thread_jobs#show', :as => 'meeting_thread_job' 
  resources :calendar_guesses
    
  constraints RegularUserConstraint.new do
    
      resources :meeting_threads do
        collection do
          post 'from_sendgrid'
        end
      end

  end

  root :to => "home#index"

  mount StripeEvent::Engine => '/stripe'
      
  devise_for :users, :controllers => { :subscriptions => 'subscriptions' }
  
  resources :users

  resources :subscriptions
  
  put 'update_plan', :to => 'subscriptions#update_plan'
  put 'update_card', :to => 'subscriptions#update_card'
  resources :plans

  match 'auth/:provider/callback', to: 'oauth_sessions#create'
  match 'auth/failure', to: redirect('/')
  

end

app/controllers/meeting_thread_jobs_controller.rb
class MeetingThreadJobsController < ApplicationController
  
  #This is just a pass through controller
  #it's model is meeting_threads but this is the viewcontroller that turks will interact with
  #hence a different viewcontroller and view paradigm

  before_filter :authorize_turker
  
  # GET /meeting_threads_jobs
  # GET /meeting_thread_jobs.json
  def index
    
    @meeting_threads = @current_user.available_jobs
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meeting_threads }
    end
  end


  # GET /meeting_thread_jobs/1
  # GET /meeting_thread_jobs/1.json
  def show
    @meeting_thread = MeetingThread.find(params[:id])
    @calendar_guess = @meeting_thread.calendar_guesses.build 
    @calendar_guess.time_zone = @meeting_thread.user.default_time_zone
    #@calendar_guess.description = @meeting_thread.html


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting_thread }
    end
  end

protected
  def authorize_turker
    authorize! :create, CalendarGuess
  end
end

app/helpers/meeting_thread_jobs_helper.rb
module MeetingThreadJobsHelper
end

app/views/meeting_thread_jobs/index.html.erb
<h2>Meetings to make</h2>

<table class = "table table-striped">
	<thead>
		<tr>
		  <th>From</th>
		  <th>Subject</th>
		  <th></th>
		</tr>
	</thead>
	<tbody>
		<% @meeting_threads.each do |meeting_thread| %>
		  <tr>
		    <td><%= meeting_thread.from %></td>
		    <td><%= meeting_thread.subject %></td>
			<td><%= link_to "Complete job", meeting_thread_job_path(meeting_thread), :class => "btn btn-mini"%></td>
		  </tr>
		<% end %>

	</tbody>
</table>

app/views/meeting_thread_jobs/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>From:</b>
  <%= @meeting_thread.from %>
</p>

<p>
  <b>To:</b>
  <%= @meeting_thread.to %>
</p>

<p>
  <b>Cc:</b>
  <%= @meeting_thread.cc %>
</p>
<p>
  <b>Subject:</b>
  <%= @meeting_thread.subject %>
</p>

<p>
  <%if @meeting_thread.html%>
  	<%= raw(@meeting_thread.html) %>
  <%elsif @meeting_thread.text%>
  	<%= @meeting_thread.text %>
  <%end%>
</p>

<p>


</p>


<%= render "calendar_guesses/calendar_guess_form"%>