config/routes.rb
class TurkerConstraint
  def initialize
    @turker_host_names = ['lvh.me', 'turker.zenlike.me', 'makemeeting.info']
  end
 
  def matches?(request)
    @turker_host_names.include?(request.host)
  end
end

class RegularUserConstraint
  def initialize
    @regular_host_names = ['localhost', 'zenlike.herokuapp.com','meetings.zenlike.me']
  end
 
  def matches?(request)
    @regular_host_names.include?(request.host)
  end
end

Zenlike::Application.routes.draw do

  get "home/index"

  
  
  
  get 'meeting_thread_jobs' => 'meeting_thread_jobs#index', :as => 'meeting_thread_jobs'
  get 'meeting_thread_jobs/:id' => 'meeting_thread_jobs#show', :as => 'meeting_thread_job' 
  resources :calendar_guesses
    
  constraints RegularUserConstraint.new do
    
      resources :meeting_threads do
        collection do
          post 'from_sendgrid'
        end
      end

  end

  root :to => "home#index"

  mount StripeEvent::Engine => '/stripe'
      
  devise_for :users, :controllers => { :subscriptions => 'subscriptions' }
  
  resources :users

  resources :subscriptions
  
  put 'update_plan', :to => 'subscriptions#update_plan'
  put 'update_card', :to => 'subscriptions#update_card'
  resources :plans

  match 'auth/:provider/callback', to: 'oauth_sessions#create'
  match 'auth/failure', to: redirect('/')
  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates_presence_of :stripe_id
  validates_uniqueness_of :stripe_id
  attr_accessible :name, :stripe_id, :price, :credits  
  has_many :subscriptions
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.order("price")
  end  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.html.erb
<div id="welcome" class="hero-unit span8">
  <h2>Zenlike plans</h2>
  <p><em>*All prices are based on a monthly subscription</em></p>
  <%if current_user.subscription%>
  	<p><em>*Your current subscription is <%=current_user.subscription.plan.name%></em></p>
  <%end%>

</div>

<div class="row span8 plans">
  <div class="span2 well">
    <div class="plan"><h2>Silver</h2></div>
    <ul class="unstyled">
      <li>10 free meeting coordinations a month</li>
    </ul>
    <h3>$9.99</h3>
    <%= link_to 'Subscribe', edit_subscription_path(current_user.subscription, :plan_name => 'Silver'), :class => 'btn btn-primary' %> 
  </div>
  <div class="span2 well featured">
    <div class="plan featured-plan"><h2>Gold</h2></div>
    <ul class="unstyled">
      <li>50 free meeting coordinations a month</li>
    </ul>
    <h3>$19.99</h3>
    <%= link_to 'Subscribe', edit_subscription_path(current_user.subscription, :plan_name => 'Gold'), :class => 'btn btn-primary' %> 
  </div>
  <div class="span2 well">
    <div class="plan"><h2>Elite</h2></div>
    <ul class="unstyled">
      <li>Unlimited meeting coordinations + virtual assistant</li>
    </ul>
    <h3>$199.99</h3>
    <%= link_to 'Subscribe', edit_subscription_path(current_user.subscription, :plan_name => 'Platinum'), :class => 'btn btn-primary' %> 
  </div>
<br/><br/>

</div>