config/routes.rb
class TurkerConstraint
  def initialize
    @turker_host_names = ['lvh.me', 'turker.zenlike.me', 'makemeeting.info']
  end
 
  def matches?(request)
    @turker_host_names.include?(request.host)
  end
end

class RegularUserConstraint
  def initialize
    @regular_host_names = ['localhost', 'zenlike.herokuapp.com','meetings.zenlike.me']
  end
 
  def matches?(request)
    @regular_host_names.include?(request.host)
  end
end

Zenlike::Application.routes.draw do

  get "home/index"

  
  
  
  get 'meeting_thread_jobs' => 'meeting_thread_jobs#index', :as => 'meeting_thread_jobs'
  get 'meeting_thread_jobs/:id' => 'meeting_thread_jobs#show', :as => 'meeting_thread_job' 
  resources :calendar_guesses
    
  constraints RegularUserConstraint.new do
    
      resources :meeting_threads do
        collection do
          post 'from_sendgrid'
        end
      end

  end

  root :to => "home#index"

  mount StripeEvent::Engine => '/stripe'
      
  devise_for :users, :controllers => { :subscriptions => 'subscriptions' }
  
  resources :users

  resources :subscriptions
  
  put 'update_plan', :to => 'subscriptions#update_plan'
  put 'update_card', :to => 'subscriptions#update_card'
  resources :plans

  match 'auth/:provider/callback', to: 'oauth_sessions#create'
  match 'auth/failure', to: redirect('/')
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zenlike</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Zenlike</a>
        <div class="nav-collapse">
          <ul class="nav">
			<%if user_signed_in?%>
				<%if can? :create, CalendarGuess%>
					<li><%= link_to "Jobs", meeting_thread_jobs_path%></li>
				<%end%>
				<%if can? :create, MeetingThread%>
					<li><%= link_to "Meeting Threads", meeting_threads_path%></li>
				<%end%>
				<%if @zendesk_login_link%>
					<li><%= link_to "Assistant", @zendesk_login_link.html_safe%></li>
				<%end%>
				<li><%= link_to current_user.email, edit_user_registration_path%></li>
				<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
			<%else%>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Sign in", new_user_session_path%></li>
			<%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>	

<div class="container">
	<% flash.each do |name, msg| %>
	  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	    <a class="close" data-dismiss="alert">×</a>
	    <%= msg %>
	  </div>
	<% end %>	
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>

</body>
</html>

app/views/layouts/turker_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zenlike</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">MakeMeeting.Info</a>
        <div class="nav-collapse">
          <ul class="nav">
			<%if user_signed_in?%>
				<%if can? :create, CalendarGuess%>
					<li><%= link_to "Jobs", meeting_thread_jobs_path%></li>
				<%end%>
				<%if can? :create, MeetingThread%>
					<li><%= link_to "Meeting Threads", meeting_threads_path%></li>
				<%end%>
				<li><%= link_to current_user.email, edit_user_registration_path%></li>
				<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
			<%else%>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
				<li><%= link_to "Sign in", new_user_session_path%></li>
			<%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>	

<div class="container">
	<% flash.each do |name, msg| %>
	  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	    <a class="close" data-dismiss="alert">×</a>
	    <%= msg %>
	  </div>
	<% end %>	
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>

</body>
</html>